name = "live-traces-site"
compatibility_date = "2026-01-01"

routes = [
  { pattern = "live-traces.necmttn.com", custom_domain = true }
]

# Cloudflare Worker that serves the built static assets.
[assets]
directory = "./dist"
not_found_handling = "single-page-application"
