/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DurableStreamsRouteImport } from './routes/durable-streams'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsTransportsRouteImport } from './routes/docs/transports'
import { Route as DocsQuickstartRouteImport } from './routes/docs/quickstart'
import { Route as DocsFrontendRouteImport } from './routes/docs/frontend'
import { Route as DocsConceptsRouteImport } from './routes/docs/concepts'
import { Route as DocsIntegrationsOpentelemetryRouteImport } from './routes/docs/integrations/opentelemetry'
import { Route as DocsIntegrationsDurableStreamsRouteImport } from './routes/docs/integrations/durable-streams'

const DurableStreamsRoute = DurableStreamsRouteImport.update({
  id: '/durable-streams',
  path: '/durable-streams',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsTransportsRoute = DocsTransportsRouteImport.update({
  id: '/transports',
  path: '/transports',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFrontendRoute = DocsFrontendRouteImport.update({
  id: '/frontend',
  path: '/frontend',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsConceptsRoute = DocsConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsIntegrationsOpentelemetryRoute =
  DocsIntegrationsOpentelemetryRouteImport.update({
    id: '/integrations/opentelemetry',
    path: '/integrations/opentelemetry',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsIntegrationsDurableStreamsRoute =
  DocsIntegrationsDurableStreamsRouteImport.update({
    id: '/integrations/durable-streams',
    path: '/integrations/durable-streams',
    getParentRoute: () => DocsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/durable-streams': typeof DurableStreamsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/frontend': typeof DocsFrontendRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/transports': typeof DocsTransportsRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/integrations/durable-streams': typeof DocsIntegrationsDurableStreamsRoute
  '/docs/integrations/opentelemetry': typeof DocsIntegrationsOpentelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/durable-streams': typeof DurableStreamsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/frontend': typeof DocsFrontendRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/transports': typeof DocsTransportsRoute
  '/docs': typeof DocsIndexRoute
  '/docs/integrations/durable-streams': typeof DocsIntegrationsDurableStreamsRoute
  '/docs/integrations/opentelemetry': typeof DocsIntegrationsOpentelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/durable-streams': typeof DurableStreamsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/frontend': typeof DocsFrontendRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/transports': typeof DocsTransportsRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/integrations/durable-streams': typeof DocsIntegrationsDurableStreamsRoute
  '/docs/integrations/opentelemetry': typeof DocsIntegrationsOpentelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/durable-streams'
    | '/docs/concepts'
    | '/docs/frontend'
    | '/docs/quickstart'
    | '/docs/transports'
    | '/docs/'
    | '/docs/integrations/durable-streams'
    | '/docs/integrations/opentelemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/durable-streams'
    | '/docs/concepts'
    | '/docs/frontend'
    | '/docs/quickstart'
    | '/docs/transports'
    | '/docs'
    | '/docs/integrations/durable-streams'
    | '/docs/integrations/opentelemetry'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/durable-streams'
    | '/docs/concepts'
    | '/docs/frontend'
    | '/docs/quickstart'
    | '/docs/transports'
    | '/docs/'
    | '/docs/integrations/durable-streams'
    | '/docs/integrations/opentelemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  DurableStreamsRoute: typeof DurableStreamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/durable-streams': {
      id: '/durable-streams'
      path: '/durable-streams'
      fullPath: '/durable-streams'
      preLoaderRoute: typeof DurableStreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/transports': {
      id: '/docs/transports'
      path: '/transports'
      fullPath: '/docs/transports'
      preLoaderRoute: typeof DocsTransportsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/frontend': {
      id: '/docs/frontend'
      path: '/frontend'
      fullPath: '/docs/frontend'
      preLoaderRoute: typeof DocsFrontendRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/concepts': {
      id: '/docs/concepts'
      path: '/concepts'
      fullPath: '/docs/concepts'
      preLoaderRoute: typeof DocsConceptsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/integrations/opentelemetry': {
      id: '/docs/integrations/opentelemetry'
      path: '/integrations/opentelemetry'
      fullPath: '/docs/integrations/opentelemetry'
      preLoaderRoute: typeof DocsIntegrationsOpentelemetryRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/integrations/durable-streams': {
      id: '/docs/integrations/durable-streams'
      path: '/integrations/durable-streams'
      fullPath: '/docs/integrations/durable-streams'
      preLoaderRoute: typeof DocsIntegrationsDurableStreamsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsConceptsRoute: typeof DocsConceptsRoute
  DocsFrontendRoute: typeof DocsFrontendRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsTransportsRoute: typeof DocsTransportsRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsIntegrationsDurableStreamsRoute: typeof DocsIntegrationsDurableStreamsRoute
  DocsIntegrationsOpentelemetryRoute: typeof DocsIntegrationsOpentelemetryRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsConceptsRoute: DocsConceptsRoute,
  DocsFrontendRoute: DocsFrontendRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsTransportsRoute: DocsTransportsRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsIntegrationsDurableStreamsRoute: DocsIntegrationsDurableStreamsRoute,
  DocsIntegrationsOpentelemetryRoute: DocsIntegrationsOpentelemetryRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  DurableStreamsRoute: DurableStreamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
