#!/usr/bin/env bun
/**
 * Mirror examples/* → examples-sandbox/* with deps rewritten for StackBlitz / CodeSandbox.
 *
 *   examples/             - workspace deps (`livetrace: workspace:*`). Repo-dev only.
 *   examples-sandbox/     - npm deps (`livetrace: ^X.Y.Z`). Standalone, embed-ready.
 *
 * Re-run whenever an example changes. Idempotent.
 */
import { existsSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { mkdir, readFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const SRC_DIR = join(ROOT, "examples");
const DST_DIR = join(ROOT, "examples-sandbox");

const PKG_VERSION = JSON.parse(readFileSync(join(ROOT, "packages/livetrace/package.json"), "utf8")).version as string;
const LIVETRACE_DEP = `^${PKG_VERSION}`;

const SKIP_DIRS = new Set(["node_modules", "dist", ".turbo", ".cache"]);

const STACKBLITZRC = JSON.stringify(
    {
        installDependencies: true,
        startCommand: "bun run dev",
        compileTrigger: "save",
        env: { ENABLE_CJS_IMPORTS: true },
    },
    null,
    2,
);

const README_NOTE = `
> **Note:** This is the **sandbox-ready** copy of the example, generated by
> [\`scripts/sync-sandbox.ts\`](../../scripts/sync-sandbox.ts).
>
> The canonical version lives at [\`examples/${"$NAME$"}\`](../../examples/${"$NAME$"})
> and uses \`livetrace: workspace:*\` for monorepo dev. This copy swaps that
> for \`livetrace: ${LIVETRACE_DEP}\` from npm so it boots inside
> StackBlitz / CodeSandbox without a workspace install.
`;

async function copyDir(src: string, dst: string): Promise<void> {
    await mkdir(dst, { recursive: true });
    for (const entry of readdirSync(src)) {
        if (SKIP_DIRS.has(entry)) continue;
        const s = join(src, entry);
        const d = join(dst, entry);
        const st = statSync(s);
        if (st.isDirectory()) {
            await copyDir(s, d);
        } else {
            const data = await readFile(s);
            writeFileSync(d, data);
        }
    }
}

function rewritePackageJson(path: string, name: string): void {
    if (!existsSync(path)) return;
    const pkg = JSON.parse(readFileSync(path, "utf8")) as {
        name?: string;
        dependencies?: Record<string, string>;
        devDependencies?: Record<string, string>;
        scripts?: Record<string, string>;
    };

    // Suffix the name so npm install treats it as a distinct package.
    pkg.name = `${name}-sandbox`;

    for (const block of [pkg.dependencies, pkg.devDependencies]) {
        if (!block) continue;
        for (const k of Object.keys(block)) {
            if (block[k]?.startsWith("workspace:")) {
                if (k === "livetrace") {
                    block[k] = LIVETRACE_DEP;
                } else {
                    delete block[k];
                }
            }
        }
    }

    writeFileSync(path, JSON.stringify(pkg, null, 2) + "\n");
}

function rewriteTsconfig(path: string): void {
    if (!existsSync(path)) return;
    const tsc = JSON.parse(readFileSync(path, "utf8")) as { extends?: string };
    if (tsc.extends?.startsWith("../../")) {
        delete tsc.extends;
        tsc satisfies Record<string, unknown>;
        // Inline the bits we actually need so the sandbox doesn't need the repo's root tsconfig.
        Object.assign(tsc, {
            compilerOptions: {
                target: "ES2022",
                module: "ESNext",
                moduleResolution: "Bundler",
                jsx: "react-jsx",
                lib: ["ES2023", "DOM", "DOM.Iterable"],
                strict: true,
                noUncheckedIndexedAccess: true,
                skipLibCheck: true,
                noEmit: true,
                types: ["bun", "react", "react-dom"],
            },
            include: ["src/**/*", "vite.config.ts"],
        });
    }
    writeFileSync(path, JSON.stringify(tsc, null, 2) + "\n");
}

async function main(): Promise<void> {
    rmSync(DST_DIR, { recursive: true, force: true });
    await mkdir(DST_DIR, { recursive: true });

    const examples = readdirSync(SRC_DIR).filter((e) => statSync(join(SRC_DIR, e)).isDirectory());
    console.log(`Found ${examples.length} examples: ${examples.join(", ")}`);

    for (const name of examples) {
        const src = join(SRC_DIR, name);
        const dst = join(DST_DIR, name);
        console.log(`  → ${relative(ROOT, dst)}`);
        await copyDir(src, dst);
        rewritePackageJson(join(dst, "package.json"), name);
        rewriteTsconfig(join(dst, "tsconfig.json"));
        writeFileSync(join(dst, ".stackblitzrc"), STACKBLITZRC);
        const readmePath = join(dst, "README.md");
        const existing = existsSync(readmePath) ? readFileSync(readmePath, "utf8") : `# ${name}\n`;
        writeFileSync(readmePath, existing + "\n" + README_NOTE.replaceAll("$NAME$", name) + "\n");
    }

    console.log(`Synced ${examples.length} sandbox example${examples.length === 1 ? "" : "s"} → ${relative(ROOT, DST_DIR)}/`);
    console.log(`livetrace dep: ${LIVETRACE_DEP}`);
}

await main();
